name: one_chore
description: A productivity app that helps users accomplish one task per day
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.9.0
  flutter: ^3.35.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  fl_chart: ^0.69.2
  flutter_local_notifications: ^18.0.1
  flutter_riverpod: ^3.0.3
  freezed_annotation: ^3.1.0
  go_router: ^14.6.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.20.2
  json_annotation: ^4.9.0
  lottie: ^3.2.0
  path_provider: ^2.1.4
  riverpod_annotation: ^3.0.3
  uuid: ^4.5.1

dev_dependencies:
  build_runner: ^2.4.14
  custom_lint: ^0.8.1
  flutter_test:
    sdk: flutter

  freezed: ^3.2.3
  json_serializable: ^6.8.0
  mocktail: ^1.0.4
  riverpod_generator: ^3.0.3
  riverpod_lint: ^3.0.3
  very_good_analysis: ^10.0.0

flutter:
  generate: true
  uses-material-design: true
